name: "Close stale issues requiring user information"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Please provide the further information requested, or the issue will be closed in 5 days."
          any-of-labels: "info-requested"
          days-before-stale: 30
          days-before-close: 5
          days-before-pr-stale: -1
          days-before-pr-close: -1
